assert(SMODS.load_file("content/backs.lua"))()
assert(SMODS.load_file("atlas/atlas.lua"))()
assert(SMODS.load_file("content/sleeves.lua"))()
assert(SMODS.load_file("content/jokers.lua"))()
assert(SMODS.load_file("content/hands.lua"))()
assert(SMODS.load_file("content/stakes.lua"))()